import { randomUUID } from 'node:crypto';
import { Kysely, CamelCasePlugin, sql } from 'kysely';
import { PostgresJSDialect } from 'kysely-postgres-js';
import * as postgres from 'postgres';
import { KyselyDB } from '../../../database/types/kysely.types';
import { up } from '../../../database/migrations/20261004T150000-sop-handbook-jobs';
import { HandbookJobStore } from './handbook-job.store';
const url=process.env.SOP_CAPTURE_TEST_DATABASE_URL;
(url?describe:describe.skip)('handbook persistent jobs: real isolated PostgreSQL',()=>{
 let db:KyselyDB,store:HandbookJobStore;const schema='handbook_'+randomUUID().replace(/-/g,'');
 const workspaceId=randomUUID(),pageId=randomUUID(),spaceId=randomUUID(),actorId=randomUUID(),renderer='a'.repeat(64),bindingHash='b'.repeat(64);
 const content={type:'doc',content:[]},binding={template:{id:'fixture',version:'1.0.0'}};
 beforeAll(async()=>{if(new URL(url).pathname!=='/sop_capture_test')throw new Error('Isolated database required');
  db=new Kysely({dialect:new PostgresJSDialect({postgres:postgres(url,{max:8,onnotice:()=>{},connection:{search_path:schema}})}),plugins:[new CamelCasePlugin()]}) as KyselyDB;
  await sql`CREATE SCHEMA ${sql.id(schema)}`.execute(db);
 });
 beforeEach(async()=>{await sql`DROP SCHEMA ${sql.id(schema)} CASCADE`.execute(db);await sql`CREATE SCHEMA ${sql.id(schema)}`.execute(db);await up(db);
  await sql`CREATE TABLE pages(id uuid,workspace_id uuid,space_id uuid,title text,content jsonb,deleted_at timestamptz)`.execute(db);
  await sql`CREATE TABLE sop_page_versions(id uuid,workspace_id uuid,space_id uuid,page_id uuid,revision integer,status text,snapshot jsonb)`.execute(db);
  await sql`INSERT INTO pages VALUES(${pageId}::uuid,${workspaceId}::uuid,${spaceId}::uuid,'Original',${JSON.stringify(content)}::text::jsonb,NULL)`.execute(db);
  store=new HandbookJobStore(db);await store.configure({workspaceId,pageId,spaceId,actorId,binding,bindingHash,autoUpdate:true});
 });
 afterAll(async()=>{await sql`DROP SCHEMA ${sql.id(schema)} CASCADE`.execute(db);await db.destroy();});
 async function version(revision=1,title='Original'){const id=randomUUID();await sql`UPDATE pages SET title=${title} WHERE id=${pageId}::uuid`.execute(db);
  await sql`INSERT INTO sop_page_versions VALUES(${id}::uuid,${workspaceId}::uuid,${spaceId}::uuid,${pageId}::uuid,${revision},'synced',${JSON.stringify({page:{title,content}})}::text::jsonb)`.execute(db);return {id,revision};}
 const request=async(v?:any)=>store.request(workspaceId,pageId,v||await version(),renderer);
 const manifest={pageId:'test-output'},prefix='private/test-attempt';
 it('concurrent identical requests have one durable identity',async()=>{const v=await version();const jobs=await Promise.all(Array.from({length:6},()=>request(v)));expect(new Set(jobs.map(j=>j.id)).size).toBe(1);expect((await store.target(workspaceId,pageId)).generation).toBe(1);});
 it('two workers cannot claim the same live lease',async()=>{await request();const claims=await Promise.all([store.claim(),new HandbookJobStore(db).claim()]);expect(claims.filter(Boolean)).toHaveLength(1);});
 it('complete result and visible pointer are committed together',async()=>{const requested=await request(),job=await store.claim();expect(await store.finish(job,manifest,prefix)).toBe(true);expect((await store.target(workspaceId,pageId)).currentJobId).toBe(requested.id);expect((await store.job(workspaceId,pageId,job.id)).manifest).toEqual(manifest);});
 it('source request deduplicates after success unless explicitly refreshed',async()=>{const v=await version(),a=await request(v);await store.finish(await store.claim(),manifest,prefix);expect((await request(v)).id).toBe(a.id);expect((await store.request(workspaceId,pageId,v,renderer,true)).id).not.toBe(a.id);});
 it('failed successor cannot remove the last complete pointer',async()=>{const a=await request();await store.finish(await store.claim(),manifest,prefix);await request(await version(2,'New'));await store.fail(await store.claim(),'LAYOUT_REQUIRED',false);expect((await store.target(workspaceId,pageId)).currentJobId).toBe(a.id);});
 it('late old job cannot overwrite a newer visible result',async()=>{await request();const old=await store.claim();const b=await request(await version(2,'New'));expect(await store.finish(await store.claim(),{pageId:'new'},prefix+'/new')).toBe(true);expect(await store.finish(old,manifest,prefix+'/old')).toBe(false);expect((await store.target(workspaceId,pageId)).currentJobId).toBe(b.id);});
 it('recovery replaces the claim token and rejects the crashed process completion',async()=>{await request();const crashed=await store.claim();await sql`UPDATE sop_handbook_jobs SET lease_until=now()-interval '1 second'`.execute(db);const resumed=await new HandbookJobStore(db).claim();expect(resumed.id).toBe(crashed.id);expect(resumed.leaseToken).not.toBe(crashed.leaseToken);expect(resumed.attempts).toBe(2);expect(await store.finish(crashed,manifest,prefix)).toBe(false);expect(await store.finish(resumed,manifest,prefix+'/recovered')).toBe(true);});
 it('expired process cannot heartbeat itself back to life',async()=>{await request();const job=await store.claim();await sql`UPDATE sop_handbook_jobs SET lease_until=now()-interval '1 second'`.execute(db);expect(await store.heartbeat(job)).toBe(false);});
 it('expired process cannot report failure on a newer claimant',async()=>{await request();const old=await store.claim();await sql`UPDATE sop_handbook_jobs SET lease_until=now()-interval '1 second'`.execute(db);const newer=await store.claim();await store.fail(old,'OLD_ERROR',false);expect((await store.job(workspaceId,pageId,newer.id)).state).toBe('running');});
 it('process restart preserves queued requests',async()=>{const job=await request();const restarted=new HandbookJobStore(db);expect((await restarted.claim()).id).toBe(job.id);});
 it('retry backoff delays claiming and retains error details',async()=>{await request();const a=await store.claim();await store.fail(a,'TEMPORARY',true);expect(await store.claim()).toBeUndefined();await sql`UPDATE sop_handbook_jobs SET next_attempt_at=now()`.execute(db);const b=await store.claim();expect(b.id).toBe(a.id);expect(b.attempts).toBe(2);});
 it('three lost leases reach a terminal failure rather than endless reclaim',async()=>{await request();for(let i=0;i<3;i++){expect(await store.claim()).toBeDefined();await sql`UPDATE sop_handbook_jobs SET lease_until=now()-interval '1 second'`.execute(db);}expect(await store.claim()).toBeUndefined();const target=await store.target(workspaceId,pageId);expect((await store.job(workspaceId,pageId,target.desiredJobId)).lastErrorCode).toBe('LEASE_EXHAUSTED');});
 it('new binding invalidates in-flight old configuration',async()=>{await request();const old=await store.claim();await store.configure({workspaceId,pageId,spaceId,actorId,binding:{...binding,newLayout:true},bindingHash:'c'.repeat(64),autoUpdate:true});expect(await store.finish(old,manifest,prefix)).toBe(false);});
 it('source edit not yet captured as a version prevents publication',async()=>{await request();const job=await store.claim();await sql`UPDATE pages SET title='Unsaved new title'`.execute(db);expect(await store.finish(job,manifest,prefix)).toBe(false);});
 it('new source version prevents old publication even before its next job is requested',async()=>{await request();const job=await store.claim();await version(2);expect(await store.finish(job,manifest,prefix)).toBe(false);});
 it('deleted source cannot be newly published',async()=>{await request();const job=await store.claim();await sql`UPDATE pages SET deleted_at=now()`.execute(db);expect(await store.finish(job,manifest,prefix)).toBe(false);});
 it('workspace scoped lookup cannot fetch another workspace job or target',async()=>{const j=await request();expect(await store.job(randomUUID(),pageId,j.id)).toBeUndefined();expect(await store.target(randomUUID(),pageId)).toBeUndefined();});
 it('older revision requests never replace the newer desired request',async()=>{const old=await version(),newer=await version(2);const b=await request(newer);await expect(request(old)).rejects.toThrow('OLDER_REQUEST_REJECTED');expect((await store.target(workspaceId,pageId)).desiredJobId).toBe(b.id);});
 it('attachment metadata change at same source revision creates a new request',async()=>{const v=await version();const a=await store.request(workspaceId,pageId,v,renderer,false,'c'.repeat(64));const b=await store.request(workspaceId,pageId,v,renderer,false,'d'.repeat(64));expect(a.id).not.toBe(b.id);});
 it('fair polling rotates past the first fifty configured targets',async()=>{for(let n=0;n<51;n++)await store.configure({workspaceId,pageId:randomUUID(),spaceId,actorId,binding,bindingHash,autoUpdate:true});
   const first=await store.candidates(),second=await store.candidates();expect(first).toHaveLength(50);expect(new Set([...first,...second].map(t=>t.pageId)).size).toBe(52);
 });
 it('disabling automatic polling retains current output and source binding',async()=>{const a=await request();await store.finish(await store.claim(),manifest,prefix);await store.stopAutomatic(workspaceId,pageId,'SOURCE_ACCESS_REVOKED');const target=await store.target(workspaceId,pageId);expect(target.autoUpdate).toBe(false);expect(target.currentJobId).toBe(a.id);expect(target.binding).toEqual(binding);expect(await store.candidates()).toHaveLength(0);});
});
