import { ConflictException } from '@nestjs/common';
import { HandbookService } from './handbook.service';
function fixture(){const store={configure:jest.fn().mockResolvedValue({})};const service=new HandbookService({} as any,store as any,{} as any,{} as any,{} as any,{} as any,{} as any,{} as any,{} as any);
 const user={id:'actor',workspaceId:'workspace'} as any,selection={id:'chapter-reader',version:'1.0.0',density:'comfortable'};
 const prepared={access:{page:{spaceId:'space'}},plan:{binding:{template:selection},summary:{counts:{blocks:2}}},token:'target-token',bindingHash:'binding-hash',version:{id:'version',revision:3},proposalHash:'proposal-hash'};
 const prepare=jest.spyOn(service as any,'prepareLayout').mockResolvedValue(prepared);const refresh=jest.spyOn(service,'refresh').mockResolvedValue({state:'queued'} as any);return{service,store,user,selection,prepared,prepare,refresh};}
describe('first-layout preview and explicit confirmation',()=>{
 it('preview returns source identity and summary without saving configuration or queuing generation',async()=>{const f=fixture();const r=await f.service.previewLayout('page',f.selection,f.user);expect(r.versionId).toBe('version');expect(r.revision).toBe(3);expect(r.summary).toEqual(f.prepared.plan.summary);expect(f.store.configure).not.toHaveBeenCalled();expect(f.refresh).not.toHaveBeenCalled();});
 it('apply recomputes the plan and passes fixed-source/target guards to the transaction',async()=>{const f=fixture();await f.service.applyLayout('page',f.selection,'proposal-hash',true,f.user);expect(f.prepare).toHaveBeenCalledWith('page',f.selection,f.user);expect(f.store.configure).toHaveBeenCalledWith(expect.objectContaining({pageId:'page',workspaceId:'workspace',actorId:'actor',binding:f.prepared.plan.binding}),{targetToken:'target-token',versionId:'version'});expect(f.refresh).toHaveBeenCalledWith('page',f.user);});
 it('stale proposal is refused before configuration writes',async()=>{const f=fixture();await expect(f.service.applyLayout('page',f.selection,'old-hash',false,f.user)).rejects.toThrow(ConflictException);expect(f.store.configure).not.toHaveBeenCalled();expect(f.refresh).not.toHaveBeenCalled();});
 it.each(['LAYOUT_TARGET_CHANGED','LAYOUT_SOURCE_CHANGED'])('transaction conflict %s never starts a replacement job',async code=>{const f=fixture();f.store.configure.mockRejectedValue(new Error(code));await expect(f.service.applyLayout('page',f.selection,'proposal-hash',false,f.user)).rejects.toThrow(ConflictException);expect(f.refresh).not.toHaveBeenCalled();});
 it('source permission failure while preparing cannot be replaced by caller-supplied binding',async()=>{const f=fixture();f.prepare.mockRejectedValue(new Error('revoked'));await expect(f.service.applyLayout('page',f.selection,'proposal-hash',true,f.user)).rejects.toThrow('revoked');expect(f.store.configure).not.toHaveBeenCalled();});
});
