import {afterEach,beforeEach,describe,expect,it,vi} from 'vitest';
import {act,cleanup,fireEvent,render,screen,waitFor,within} from '@testing-library/react';
import {MantineProvider} from '@mantine/core';
import {webcrypto} from 'node:crypto';
import PiModelSettings from './pi-model-settings';
import {connectionForm,serviceEntries} from './pi-model-services-types';
import type {ModelServicesView,ServiceConnection,ServicePreset} from './pi-model-services-types';
const mocks=vi.hoisted(()=>({request:vi.fn(),saved:vi.fn(),close:vi.fn()}));
vi.mock('./pi-workbench-api',()=>({piRequest:mocks.request,piError:()=> '旧版读取失败'}));
const seed=[{id:'kimi-k3',name:'Kimi K3',contextWindow:200000,outputWindow:8000,capabilities:{tools:true,streaming:true}},{id:'kimi-k2.7-code',name:'Kimi K2.7 Code',contextWindow:100000,outputWindow:4000}];
const preset=(id='kimi'):ServicePreset=>({id,category:'chat',name:id==='kimi'?'Kimi（月之暗面）':id==='qwen'?'通义千问':'Ollama（本地模型）',api:'openai-completions',defaultBaseUrl:id==='ollama'?'http://127.0.0.1:11434/v1':`https://${id}.example.invalid/v1`,authMode:id==='ollama'?'none':'bearer',execution:'supported',unavailableReason:null,keyOptional:id==='ollama',seedOnConnect:id!=='ollama',supportsModelDiscovery:true,icon:null,monochrome:false,models:seed,alternateBaseUrls:[],links:[]});
const model=(id='kimi-k3')=>({modelId:id,label:id,reasoning:false,contextWindow:65536,maxTokens:8192,input:['text'],capabilities:{tools:true},origin:'catalog' as const});
let view:ModelServicesView;
function tree(opened=true){return <MantineProvider env="test"><PiModelSettings opened={opened} onClose={mocks.close} onSaved={mocks.saved}/></MantineProvider>;}
async function ready(){const rendered=render(tree());await screen.findByRole('button',{name:'选择供应商 Kimi（月之暗面）'});return rendered;}
function setSaved(){view.connections=[{provider:'kimi',presetId:'kimi',name:'Kimi（月之暗面）',category:'chat',api:'openai-completions',baseUrl:preset().defaultBaseUrl,authMode:'bearer',configured:true,keySet:true,models:[model(),model('kimi-k2.7-code')],hidden:[],status:{state:'saved'}}];}
beforeEach(()=>{
 const names=['语言模型','图像生成','视频生成','语音合成','语音识别','文档解析','网络搜索'],ids=['chat','image','video','tts','asr','document','webSearch'] as const;
 view={schema:'sop.model-services/1',revision:'10000000-0000-4000-8000-000000000001',allowLoopback:true,catalog:{revision:'reference',reference:{commit:'fixed',capturedAt:'2026-10-05'},categories:ids.map((id,index)=>({id,label:names[index],execution:index===0?'supported':'pending',providers:index===0?[preset(),preset('qwen'),preset('ollama')]:[{...preset('pending-'+id),id:'pending-'+id,category:id,name:names[index]+'服务',execution:'pending',unavailableReason:'执行接入尚未完成，不保存无效凭据。'}]}))},connections:[]};
 mocks.saved.mockReset();mocks.close.mockReset();mocks.request.mockReset().mockImplementation(async(route,body)=>{
  if(route==='provider-settings')return structuredClone(view);
  if(route==='provider-change'){
   const change=body.change;
   if(change.kind==='save-connection'){
    let connection=view.connections.find(item=>item.provider===change.provider);
    if(!connection){connection={provider:change.provider,presetId:change.presetId,name:change.name,category:'chat',api:change.api,baseUrl:change.baseUrl,authMode:change.authMode,configured:true,keySet:change.authMode!=='none',models:change.presetId&&change.presetId!=='ollama'?[model(),model('kimi-k2.7-code')]:[],hidden:[],status:{state:'saved'}};view.connections.push(connection);}
    else{connection.baseUrl=change.baseUrl;connection.status={state:'saved'};}
   }else if(change.kind==='upsert-model'){const connection=view.connections.find(item=>item.provider===change.provider)!;connection.models=connection.models.filter(item=>item.modelId!==change.model.modelId);connection.models.push({...change.model,origin:'manual'});}
   else if(change.kind==='hide-model'){const connection=view.connections.find(item=>item.provider===change.provider)!;connection.models=connection.models.filter(item=>item.modelId!==change.modelId);connection.hidden.push(change.modelId);}
   else if(change.kind==='remove-connection')view.connections=view.connections.filter(item=>item.provider!==change.provider);
   view.revision='20000000-0000-4000-8000-000000000001';return structuredClone(view);
  }
  if(route==='provider-test')return {view:structuredClone(view),success:true,message:'已收到所选模型的有效回复。'};
  if(route==='provider-discover')return {view:structuredClone(view),total:2,added:1,removed:0};
  throw new Error('Unexpected route '+route);
 });
 Object.defineProperty(document,'fonts',{configurable:true,value:new EventTarget()});Object.defineProperty(window,'matchMedia',{configurable:true,value:vi.fn().mockImplementation(()=>({matches:false,addEventListener(){},removeEventListener(){},addListener(){},removeListener(){}}))});vi.stubGlobal('ResizeObserver',class{observe(){}unobserve(){}disconnect(){}});vi.stubGlobal('crypto',webcrypto);
});
afterEach(()=>{cleanup();vi.unstubAllGlobals();});
describe('catalog-first model services',()=>{
 it('first launch lists all capability categories, providers and default models without creating an account',async()=>{await ready();expect(screen.getAllByRole('tab')).toHaveLength(7);expect(screen.getByRole('button',{name:'选择供应商 通义千问'})).toBeTruthy();expect(screen.getByRole('region',{name:'服务商模型列表'}).textContent).toContain('Kimi K3');expect((screen.getByLabelText('服务地址') as HTMLInputElement).value).toBe(preset().defaultBaseUrl);expect(screen.queryByText('聊天补全兼容接口')).toBeNull();expect(mocks.request.mock.calls.some(([route])=>route==='provider-change')).toBe(false);});
 it('a built-in service needs only the supplied key, not a hand-created model or protocol',async()=>{await ready();fireEvent.change(screen.getByLabelText('访问密钥'),{target:{value:'synthetic-ui-key'}});fireEvent.click(screen.getByRole('button',{name:'保存配置'}));await waitFor(()=>expect(mocks.saved).toHaveBeenCalledTimes(1));const payload=mocks.request.mock.calls.find(([route])=>route==='provider-change')?.[1];expect(payload.change).toMatchObject({kind:'save-connection',provider:'kimi',presetId:'kimi',api:'openai-completions',baseUrl:preset().defaultBaseUrl,apiKey:'synthetic-ui-key'});expect(payload.change.model).toBeUndefined();await waitFor(()=>expect((screen.getByLabelText('访问密钥') as HTMLInputElement).value).toBe(''));});
 it('rejects an empty first-time cloud key without any write',async()=>{await ready();fireEvent.click(screen.getByRole('button',{name:'保存配置'}));expect(screen.getByText('请填写此供应商的访问密钥。')).toBeTruthy();expect(mocks.request.mock.calls.some(([route])=>route==='provider-change')).toBe(false);});
 it('shows real saved/verified distinction and tests a saved selected model',async()=>{setSaved();await ready();expect(screen.getAllByText('已保存 · 未验证').length).toBeGreaterThan(0);fireEvent.click(screen.getByRole('button',{name:'测试连接'}));await screen.findByText('已收到所选模型的有效回复。');expect(mocks.request.mock.calls.find(([route])=>route==='provider-test')?.[1]).toEqual({request:{provider:'kimi',revision:view.revision,modelId:'kimi-k3'}});});
 it('failed connectivity is not replaced with a success message',async()=>{setSaved();await ready();mocks.request.mockResolvedValueOnce({view:structuredClone(view),success:false,message:'供应商拒绝访问'});fireEvent.click(screen.getByRole('button',{name:'测试连接'}));await screen.findByText('供应商拒绝访问');expect(screen.queryByText('已收到所选模型的有效回复。')).toBeNull();});
 it('never sends an edited but unsaved address to the test or discovery endpoint',async()=>{setSaved();await ready();fireEvent.change(screen.getByLabelText('服务地址'),{target:{value:'https://new.example.invalid/v1'}});expect((screen.getByRole('button',{name:'测试连接'}) as HTMLButtonElement).disabled).toBe(true);expect((screen.getByRole('button',{name:'拉取模型'}) as HTMLButtonElement).disabled).toBe(true);});
 it('can save a local provider without asking for an invented key or automatically installed models',async()=>{await ready();fireEvent.click(screen.getByRole('button',{name:'选择供应商 Ollama（本地模型）'}));expect(screen.queryByLabelText('访问密钥')).toBeNull();fireEvent.click(screen.getByRole('button',{name:'保存配置'}));await waitFor(()=>expect(mocks.saved).toHaveBeenCalled());expect(mocks.request.mock.calls.find(([route])=>route==='provider-change')?.[1].change).toMatchObject({provider:'ollama',authMode:'none',apiKey:''});expect(view.connections[0].models).toHaveLength(0);});
 it('other categories are honest pending catalogs with no fake key-save action',async()=>{await ready();fireEvent.click(screen.getByRole('tab',{name:'图像生成'}));expect(screen.getByText('执行接入尚未完成，不保存无效凭据。')).toBeTruthy();expect(screen.queryByLabelText('访问密钥')).toBeNull();expect(screen.queryByRole('button',{name:'保存配置'})).toBeNull();});
 it('switching suppliers never carries an unsaved secret to another provider',async()=>{await ready();fireEvent.change(screen.getByLabelText('访问密钥'),{target:{value:'do-not-carry-over'}});fireEvent.click(screen.getByRole('button',{name:'选择供应商 通义千问'}));fireEvent.click(screen.getByRole('button',{name:'放弃修改'}));expect((screen.getByLabelText('访问密钥') as HTMLInputElement).value).toBe('');expect((screen.getByLabelText('服务地址') as HTMLInputElement).value).toBe(preset('qwen').defaultBaseUrl);});
 it('discarding edits and selecting the same provider also restores the saved form',async()=>{await ready();fireEvent.change(screen.getByLabelText('访问密钥'),{target:{value:'discard-me'}});fireEvent.click(screen.getByRole('button',{name:'选择供应商 Kimi（月之暗面）'}));fireEvent.click(screen.getByRole('button',{name:'放弃修改'}));expect((screen.getByLabelText('访问密钥') as HTMLInputElement).value).toBe('');});
 it('custom connections remain supported and a renamed identifier becomes the selected saved account',async()=>{await ready();fireEvent.click(screen.getByRole('button',{name:'添加自定义供应商'}));fireEvent.change(screen.getByLabelText('服务商标识'),{target:{value:'custom-team'}});fireEvent.change(screen.getByLabelText('显示名称'),{target:{value:'团队模型服务'}});fireEvent.change(screen.getByLabelText('访问密钥'),{target:{value:'synthetic-team-key'}});fireEvent.change(screen.getByLabelText('服务地址'),{target:{value:'https://company.example.invalid/v1'}});fireEvent.click(screen.getByRole('button',{name:'保存配置'}));await screen.findByRole('button',{name:'选择供应商 团队模型服务'});expect(screen.getByRole('button',{name:'选择供应商 团队模型服务'}).getAttribute('aria-pressed')).toBe('true');fireEvent.click(screen.getByRole('button',{name:'新建模型'}));fireEvent.change(screen.getByLabelText('模型编号'),{target:{value:'team-model'}});fireEvent.click(screen.getByRole('button',{name:'保存模型'}));await waitFor(()=>expect(mocks.request.mock.calls.filter(([route])=>route==='provider-change')).toHaveLength(2));expect(mocks.request.mock.calls.filter(([route])=>route==='provider-change')[1][1].change.provider).toBe('custom-team');});
 it('existing models are edited without resending provider credentials',async()=>{setSaved();await ready();fireEvent.click(screen.getByRole('button',{name:'编辑模型 kimi-k3'}));fireEvent.change(screen.getByLabelText('显示名称'),{target:{value:'日常首选模型'}});fireEvent.click(screen.getByRole('button',{name:'保存模型'}));await waitFor(()=>expect(mocks.saved).toHaveBeenCalled());const payload=mocks.request.mock.calls.find(([route])=>route==='provider-change')?.[1].change;expect(payload.model.label).toBe('日常首选模型');expect(payload.apiKey).toBeUndefined();expect(payload.model.apiKey).toBeUndefined();});
 it('removing a model requires confirmation and preserves other models',async()=>{setSaved();await ready();fireEvent.click(screen.getByRole('button',{name:'移除模型 kimi-k3'}));expect(mocks.request.mock.calls.some(([route])=>route==='provider-change')).toBe(false);fireEvent.click(within(screen.getByRole('dialog',{name:'移除这个模型？'})).getByRole('button',{name:'确认'}));await waitFor(()=>expect(mocks.saved).toHaveBeenCalled());expect(view.connections[0].models.map(model=>model.modelId)).toEqual(['kimi-k2.7-code']);});
 it('model discovery reports only the server-confirmed saved result',async()=>{setSaved();await ready();fireEvent.click(screen.getByRole('button',{name:'拉取模型'}));await screen.findByText(/已完整拉取2个模型，新增1个/);expect(mocks.request.mock.calls.find(([route])=>route==='provider-discover')?.[1]).toEqual({request:{provider:'kimi',revision:view.revision}});});
 it('a configuration response arriving after the modal closed is ignored',async()=>{let done!:(value:unknown)=>void;mocks.request.mockImplementation(()=>new Promise(resolve=>done=resolve));const rendered=render(tree());await waitFor(()=>expect(done).toBeTypeOf('function'));rendered.rerender(tree(false));await act(async()=>done(view));expect(screen.queryByRole('button',{name:'选择供应商 Kimi（月之暗面）'})).toBeNull();});
 it('saved configuration changes are not described as successfully tested',async()=>{await ready();fireEvent.change(screen.getByLabelText('访问密钥'),{target:{value:'synthetic-key'}});fireEvent.click(screen.getByRole('button',{name:'保存配置'}));await waitFor(()=>expect(mocks.saved).toHaveBeenCalled());expect(screen.queryByText('验证通过')).toBeNull();expect(mocks.request.mock.calls.some(([route])=>route==='provider-test')).toBe(false);});
});
it('entry generation includes every built-in even when the workspace has no saved providers',()=>{expect(serviceEntries(view,'chat').map(item=>item.id)).toEqual(['kimi','qwen','ollama']);});
it('a connection form never rehydrates a hidden credential from server metadata',()=>{setSaved();const entry=serviceEntries(view,'chat')[0];expect(connectionForm(entry).apiKey).toBe('');expect(entry.connection?.keySet).toBe(true);});
