export type ServiceCategory='chat'|'image'|'video'|'tts'|'asr'|'document'|'webSearch';
export type ServiceModel={modelId:string;label:string;reasoning:boolean;contextWindow:number;maxTokens:number;input:string[];compat?:object;capabilities?:{streaming?:boolean;tools?:boolean;vision?:boolean};origin:'catalog'|'manual'|'discovered';catalogRevision?:string};
export type CatalogModel={id:string;name:string;contextWindow?:number;outputWindow?:number;capabilities?:{streaming?:boolean;tools?:boolean;vision?:boolean;thinking?:unknown}};
export type ServicePreset={id:string;category:ServiceCategory;name:string;api:string;defaultBaseUrl:string;baseUrlPlaceholder?:string;authMode:string;execution:'supported'|'pending';unavailableReason:string|null;setupHint?:string;keyOptional:boolean;seedOnConnect:boolean;supportsModelDiscovery:boolean;icon:string|null;monochrome:boolean;models:CatalogModel[];alternateBaseUrls:{label:string;url:string}[];links:{label:string;url:string}[]};
export type ServiceConnection={provider:string;presetId:string|null;category:ServiceCategory;name:string;api:string;baseUrl:string;authMode:string;configured:boolean;keySet:boolean;models:ServiceModel[];hidden:string[];status:{state:'saved'|'passed'|'failed';modelId?:string;checkedAt?:string;message?:string;code?:string|null};discovery?:{checkedAt:string;received:number;added:number;removed:number}};
export type ModelServicesView={schema:'sop.model-services/1';revision:string;catalog:{revision:string;reference:{commit:string;capturedAt:string};categories:{id:ServiceCategory;label:string;execution:'supported'|'pending';providers:ServicePreset[]}[]};connections:ServiceConnection[];allowLoopback:boolean};
export type ServiceEntry={id:string;preset:ServicePreset|null;connection:ServiceConnection|null;name:string};
export type ConnectionForm={provider:string;presetId:string|null;name:string;api:string;baseUrl:string;apiKey:string;authMode:string;clearKey?:boolean};
export function serviceEntries(view:ModelServicesView,category:ServiceCategory):ServiceEntry[]{
 const catalog=view.catalog.categories.find(item=>item.id===category)?.providers||[],connections=view.connections.filter(item=>item.category===category),placed=new Set<string>();
 const entries=catalog.map(preset=>{const connection=connections.find(item=>item.provider===preset.id&&item.presetId===preset.id)||null;if(connection)placed.add(connection.provider);return {id:preset.id,preset,connection,name:connection?.name||preset.name};});
 const extras=connections.filter(item=>!placed.has(item.provider)).map(connection=>({id:connection.provider,preset:catalog.find(preset=>preset.id===connection.presetId)||null,connection,name:connection.name}));
 return [...entries,...extras];
}
export function connectionForm(entry:ServiceEntry):ConnectionForm{
 const {connection,preset}=entry;return {provider:connection?.provider||entry.id,presetId:connection?.presetId??preset?.id??null,name:connection?.name||entry.name,api:connection?.api||preset?.api||'openai-completions',baseUrl:connection?.baseUrl??preset?.defaultBaseUrl??'',apiKey:'',authMode:connection?.authMode||preset?.authMode||'bearer'};
}
export const modelState=(connection:ServiceConnection|null)=>!connection?'未配置':connection.status.state==='passed'?'验证通过':connection.status.state==='failed'?'验证失败':'已保存 · 未验证';
export function requestAddress(form:Pick<ConnectionForm,'api'|'baseUrl'>){const suffix=form.api==='anthropic-messages'?'messages':form.api==='openai-responses'?'responses':'chat/completions';return form.baseUrl?form.baseUrl.replace(/\/$/,'')+'/'+suffix:'';}
export function countLabel(value?:number){if(!value)return null;return value>=1000000?`${Math.round(value/10000)/100}百万词元`:value>=1000?`${Math.round(value/100)/10}千词元`:`${value}词元`;}
export function presetModels(entry:ServiceEntry):ServiceModel[]{return entry.connection?.models||entry.preset?.models.map(model=>({modelId:model.id,label:model.name,contextWindow:model.contextWindow||65536,maxTokens:Math.min(model.outputWindow||8192,model.contextWindow||65536),reasoning:!!model.capabilities?.thinking,input:model.capabilities?.vision?['text','image']:['text'],capabilities:model.capabilities,origin:'catalog'}))||[];}
export function providerError(error:unknown):string{
 const code=(error as {response?:{data?:{message?:string}}})?.response?.data?.message;
 const messages:Record<string,string>={PI_MODEL_SETTINGS_CHANGED:'配置已被其他操作修改，请重新读取后再保存。',PI_PROVIDER_REENTER_KEY:'服务地址或认证方式发生变化，请重新填写密钥，避免把原密钥发送到不同服务。',PI_MODEL_KEY_REQUIRED:'请填写此供应商的访问密钥。',PI_PROVIDER_CLEAR_KEY_REQUIRED:'切换到无密钥认证前，需要明确清除原访问密钥。',PI_MODEL_CONFIG_INVALID:'请核对服务地址、协议和模型参数。',PI_PROVIDER_NOT_CONFIGURED:'请先保存这个服务商的连接配置。',PI_PROVIDER_UNSUPPORTED:'此服务的专用执行适配尚未完成，不能保存成可用服务。',PI_PROVIDER_AUTH_FAILED:'访问密钥或账户权限未通过供应商验证。',PI_PROVIDER_ADDRESS_DENIED:'这个地址不在允许访问的模型服务范围内。',PI_PROVIDER_ENDPOINT_NOT_FOUND:'此服务没有提供对应接口，可继续使用预置目录或手工添加模型。',PI_PROVIDER_DISCOVERY_UNSUPPORTED:'该服务不提供统一模型列表，请填写真实部署名或自行添加模型。',PI_DISCOVERY_INCOMPLETE:'模型列表未完整获取，已有模型没有被修改。',PI_DISCOVERY_TOO_LARGE:'返回的模型数量超出本次限额，已有目录保持不变。',PI_PROVIDER_DNS_FAILED:'服务域名解析失败，请检查地址和网络。',PI_PROVIDER_NETWORK_FAILED:'服务连接失败，请检查网络和运行状态。',PI_PROVIDER_REDIRECT_DENIED:'已阻止携带密钥跳转，请填写最终接口地址。',PI_PROVIDER_RATE_LIMITED:'供应商返回限流或额度限制，请核对账户。',PI_PROVIDER_TIMEOUT:'请求超时，没有自动重试。',PI_PROVIDER_RESPONSE_INVALID:'返回内容不是有效模型接口响应，未更新目录。',PI_PROVIDER_DIAGNOSTIC_BUSY:'这个服务正在测试或拉取模型，请等本次操作结束。',PI_MODEL_SETTINGS_BUSY:'请先停止正在运行的智能体，再修改模型配置。',PI_MODEL_ADMIN_REQUIRED:'只有当前工作空间管理员可以管理模型服务。'};
 return code&&messages[code]?messages[code]:'操作未完成。请核对连接与权限后重试；已有配置没有被当作验证成功。';
}
